[package]
name = "ejkmer-builder"
version = "0.1.0"
edition = "2024"

[dependencies]
ej-builder-sdk = "0.5.0"
num_cpus = "1.17.0"
tokio = { version = "1.46.1", features = [
	"macros",
	"rt-multi-thread",
	"process",
] }
